PRAGMA FOREIGN_KEYS = ON;

DROP TABLE IF EXISTS Teste;
CREATE TABLE Teste (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    cpf TEXT NOT NULL UNIQUE
);

INSERT INTO Teste (nome, cpf) VALUES ("NomeTeste", "999.999.999-99");
INSERT INTO Teste (nome, cpf) VALUES ("NomeTeste2", "111.111.111-11");

-- SELECT * FROM Teste;
